name: Process Issues Match

on:
  issues:
    types: [opened, edited]

jobs:
  process_issues_match:
    runs-on: windows-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Get Match Info
        id: get_match
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const label = 'match';
            const date = new Date();
            
            const formattedDate = `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`;
            const issuesTitle = issue.title.replace(/ /g,'|');
            const matchInfo = `|${formattedDate}|${issuesTitle}|`;
            
            console.log(`Issue Title: ${issue.title}`);
            console.log(`Issue Labels: ${issue.labels.map(l => l.name).join(', ')}`);
            console.log(`Match Info: ${matchInfo}`);
            
            if (issue.labels.some(l => l.name === label)) {
              return matchInfo;
            }
            return `No Match Info`;
          
      - name: Append Match Info to Match List
        if: steps.get_match.outputs.result != 'No Match Info'
        run: |
          echo ${{steps.get_match.outputs.result}} >> "Match List.md"

      - name: Append Match Info to Match List
        if: steps.get_match.outputs.result != 'No Match Info'
        run: |
          echo "Updateing Rating List..."
          ./Bigelo.exe -JustRateIt
          echo "Updated Rating List!"

      - name: Close Issue
        uses: actions/github-script@v7
        if: steps.get_match.outputs.result != 'No Match Info'
        with:
          script: |
            const issue_number = context.issue.number;
            const issue_title = context.payload.issue.title;
            const github = require('@actions/github');
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            await octokit.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              state: 'closed'
            });

      - name: Commit Changes
        if: steps.get_match.outputs.result != 'No Match Info'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add 'Match List.md'
          git add 'README.md'
          git commit -m '${{ steps.get_match.outputs.result }} -> Rating'
          git push
